// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6LMVwBcz5YYwAkgOcH7ppM-56A0ixB4',
    appId: '1:820585508854:web:19521767d4ff161af0e1d7',
    messagingSenderId: '820585508854',
    projectId: 'e-commerce-app-7fc88',
    authDomain: 'e-commerce-app-7fc88.firebaseapp.com',
    storageBucket: 'e-commerce-app-7fc88.appspot.com',
    measurementId: 'G-6H49TDQDD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXfe_LBNETJlcsmsjR18Mok0waKHVEng',
    appId: '1:820585508854:android:7b7fe1e57dc634edf0e1d7',
    messagingSenderId: '820585508854',
    projectId: 'e-commerce-app-7fc88',
    storageBucket: 'e-commerce-app-7fc88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Pqe3BaUZkFUnSjPHS00LCp725jkf1UE',
    appId: '1:820585508854:ios:485ec10dd149ec1df0e1d7',
    messagingSenderId: '820585508854',
    projectId: 'e-commerce-app-7fc88',
    storageBucket: 'e-commerce-app-7fc88.appspot.com',
    iosClientId: '820585508854-a22co6l9afqkv6aapdodl246bvgfmbd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
